version: '2'

services:
  postgres:
    image: 'postgres'
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  redis:
    image: 'redis'
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/var/lib/redis/data'

  jobs:
    depends_on:
      - 'postgres'
      - 'redis'
      - 'app'
    build: .
    command: bash start_jobs
    volumes:
      - '.:/secret-friend'
    volumes_from:
      - box

  app:
    depends_on:
      - 'postgres'
      - 'redis'
    build: .
    command: bash setup
    ports:
      - '3000:3000'
    volumes:
      - '.:/secret-friend'
    volumes_from:
      - box

  box:
    image: busybox
    volumes:
      - /box

volumes:
  redis:
  postgres:
  box: